### ISSUE TITLE
OS X: Unable to find previously closed device / random crashes when closing device

### ISSUE THREAD

**Issue by davidaramantSEP** [signal11/hidapi#114]
OS X 10.8.3, latest version from git, USB device is known to be good (we have been using it for 7 years on Windows).

Our application has a talks to a proprietary USB IR dongle (our 'transport') which in turn talks to a variety of IR devices.  Our connect loop looks something like this in pseudo code:

```
scan for and open all supported USB transports    
    for each transport
        for each device protocol we support
            write to transport (this instructs it to send IR commands)
            read with timeout
close all open devices
```

The above sequence happens in a loop with a timeout (around 30 seconds).  There are usually multiple writes/reads for each device protocol; the end result being that we send tons of these requests to the HID layer in a short period of time.

We are seeing problems with the hidapi library that I think are related:
- If a device is unplugged and replugged, the library will never find it again when returning the attached USB devices.  I just put in a hack that activates/deactivates the library before/after each connection attempt - with this hack, it _does_ find the device again.
- When closing a device, there is a fair chance it will crash and bring down the entire process.  We have resorted to sleeping the thread that accesses hidapi for 50ms after each read/write/close.  This helps, but does not eliminate the problem.
- After a while, writes will start taking 15s to execute.  It will most likely crash when closing the device if this happens.

It feels to me like the device is not being properly closed or there is a race condition.  The stack traces following a crash always include something about HID callbacks, which seems related:

```
Thread 1 (process 60420):
#0  0x99ce5095 in __wait4 ()
#1  0x95a28996 in waitpid$UNIX2003 ()
#2  0x000bc972 in mono_handle_native_sigsegv (signal=11, ctx=0x9dafe0) at mini-exceptions.c:2331
#3  0x0005da05 in mono_arch_handle_altstack_exception (sigctx=0x9dafe0, fault_addr=0x70000020, stack_ovf=0) at exceptions-x86.c:1135
#4  0x000e90d1 in mono_sigsegv_signal_handler (_dummy=11, info=0x9dafa0, context=0x9dafe0) at mini.c:6379
#5  <signal handler called>
#6  0x970dda87 in objc_msgSend ()
#7  0x00000014 in ?? ()
#8  0x940e2516 in __IOHIDDeviceReportCallbackRegistered ()
#9  0x09a3d80b in IOHIDDeviceClass::_hidReportHandlerCallback ()
#10 0x09a3fcf1 in IOHIDQueueClass::queueEventSourceCallback ()
#11 0x09a3b941 in IOHIDDeviceClass::_cfmachPortCallback ()
#12 0x9602847f in __CFMachPortPerform ()
#13 0x96028335 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ ()
#14 0x96027f62 in __CFRunLoopDoSource1 ()
#15 0x9605dcfa in __CFRunLoopRun ()
#16 0x9605d02a in CFRunLoopRunSpecific ()
#17 0x9605ce9b in CFRunLoopRunInMode ()
#18 0x98f37f5a in RunCurrentEventLoopInMode ()
#19 0x98f37cc9 in ReceiveNextEventCommon ()
#20 0x98f37b44 in BlockUntilNextEventMatchingListInMode ()
#21 0x963779aa in _DPSNextEvent ()
#22 0x963771dc in -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] ()
#23 0x9636d63c in -[NSApplication run] ()
#24 0x96310666 in NSApplicationMain ()
#25 0x043871e3 in ?? ()
#26 0x04387008 in ?? ()
#27 0x00972fcc in ?? ()
#28 0x00973117 in ?? ()
#29 0x000f251d in mono_jit_runtime_invoke (method=0x7c211c1c, obj=0x0, params=0xbfff7758, exc=0x0) at mini.c:6261
#30 0x001d90fa in mono_runtime_invoke (method=0x7c211c1c, obj=0x0, params=0xbfff7758, exc=0x0) at object.c:2830
#31 0x001dbeec in mono_runtime_exec_main (method=0x7c211c1c, args=0x99bf30, exc=0x0) at object.c:4072
#32 0x001db0ac in mono_runtime_run_main (method=0x7c211c1c, argc=1, argv=0xbfff7940, exc=0x0) at object.c:3688
#33 0x000566e5 in mono_jit_exec (domain=0x50ae00, assembly=0x7ab38d60, argc=2, argv=0xbfff793c) at driver.c:954
#34 0x0000a43e in main ()
```

With the hack to activate/deactivate hidapi I saw a different crash which also seems to be related to threading:

```
Attaching to process 59957.
/tmp/mono-gdb-commands.E7Hq30:1: Error in sourced command file:
error on line 986 of "/SourceCache/gdb/gdb-1824/src/gdb/macosx/macosx-nat-mutils.c" in function "thread_t macosx_primary_thread_of_task(task_t)": (ipc/send) invalid destination port (0x10000003)
```

There are a number of complications with us attempting to debug this issue:
- The application is a port of a Windows .NET application.  We are using Xamarin.Mac to run the app using Mono.  The only native code we are directly using is hidapi.
- I cannot reproduce any of these issues using the Test GUI.  I might try later to hack it by automating a bunch of writes/reads so it more closely mimics the behavior of our app.
- Since we are using a proprietary USB device, there's probably no way we could provide code for anyone to reproduce the issue.
- We know virtually nothing about native Mac development.

We're kind of stuck.  I think with a combination of hacks we might be able to limp along, but it would be better if we got the bottom of what is happening.  Any ideas or suggestions you have would be appreciated.

**Comment by nyholku** [comment]
Three years later... any news on this?

In my HIDAPI clone  (PureJavaHidApi) I'm experiencing something similar on Yosemite. My lib is Java but the code logic was lifted from HIDAPI and is almost identical.

If I open a device and unplug/replug it device, then I cannot open it again. 

I traced this to the fact that after unplugging IOHIDManagerCopyDevices still returns a list where the device is present even if it has been unplugged. After re-plugging the list then contains to instances of that device.

When the list is then searched the wrong ('old') device is found and naturally opening that fails.

So somehow the device is not properly closed (in my code) but left dangling. I've tried various ways to close the device in the removal call back but without success.

As a work around I changed my open code to use the last matching entry in the list returned by IOHIDManagerCopyDevices, this improves things but unfortunately sometimes the latest plugged in incarnation of the device is not the last in the list. 

Anyway, posting this here just in case this issue is still unsolved or someone else can find some use for this titbit of debugging information. And also fishing for solution to my problem of course ;)

**Comment by nyholku** [comment]
Posting this here also for completeness, i.e. while my previous post was about PureJavaHidApi and not signal11/hidapi I'm posting the solution here for posterity in case someone ends up looking for solution to this kind of behaviour.

After spending all spare time for six days finally nailed it to this:

I did not call

    IOHIDManagerSetDeviceMatching(hidmgr, null);

before (in device enumeration) calling:

    IOHIDManagerCopyDevices(hidmgr);

What an insidious feature in IOKit, without that call everything seems to work,
except if you unplug a device then something is left dangling inside IOKit and
IOHIDManagerCopyDevices will return the unplugged device among other devices.

br Kusti
